In [1]:
import numpy as np 

In [12]:
a=np.array([1,2,3])
aa=np.array([[1,2,3],[1,2,3]])
b=np.array([1])
c=np.array([1,2])
d=np.array([1,2,3])

In [22]:
#“ * ”运算，普通乘法，对应位置做乘法,2个乘数的列数一一对应或者是一对多
print(a*b)
print(a*aa)
print(aa*a)
print(aa*b)
print(b*aa)

[1 2 3]
[[1 4 9]
 [1 4 9]]
[[1 4 9]
 [1 4 9]]
[[1 2 3]
 [1 2 3]]
[[1 2 3]
 [1 2 3]]


In [23]:
#“ / ”运算，普通乘法，对应位置做乘法,2个乘数的列数一一对应或者是一对多
print(a/b)
print(a/aa)
print(aa/a)
print(aa/b)
print(b/aa)

[1. 2. 3.]
[[1. 1. 1.]
 [1. 1. 1.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[1. 2. 3.]
 [1. 2. 3.]]
[[1.         0.5        0.33333333]
 [1.         0.5        0.33333333]]


In [24]:
#“ + ”运算，普通乘法，对应位置做乘法,2个乘数的列数一一对应或者是一对多
print(a+b)
print(a+aa)
print(aa+a)
print(aa+b)
print(b+aa)

[2 3 4]
[[2 4 6]
 [2 4 6]]
[[2 4 6]
 [2 4 6]]
[[2 3 4]
 [2 3 4]]
[[2 3 4]
 [2 3 4]]


In [25]:
#“ - ”运算，普通乘法，对应位置做乘法,2个乘数的列数一一对应或者是一对多
print(a-b)
print(a-aa)
print(aa-a)
print(aa-b)
print(b-aa)
a*aa

[0 1 2]
[[0 0 0]
 [0 0 0]]
[[0 0 0]
 [0 0 0]]
[[0 1 2]
 [0 1 2]]
[[ 0 -1 -2]
 [ 0 -1 -2]]


array([[1, 4, 9],
       [1, 4, 9]])

In [ ]:
#总结
#加减乘除，要求列数一一对应，或者是一对多，如果n对m n不等于m，将报错。
