In [2]:
import numpy as np 

In [3]:
a=np.array([1,2,3])
aa=np.array([[1,2,3],[1,2,3]])
b=np.array([1])
c=np.array([1,2])
d=np.array([1,2,3])

In [22]:
#“ * ”运算，普通乘法，对应位置做乘法,2个乘数的列数一一对应或者是一对多
print(a*b)
print(a*aa)
print(aa*a)
print(aa*b)
print(b*aa)

[1 2 3]
[[1 4 9]
 [1 4 9]]
[[1 4 9]
 [1 4 9]]
[[1 2 3]
 [1 2 3]]
[[1 2 3]
 [1 2 3]]


In [23]:
#“ / ”运算，普通乘法，对应位置做乘法,2个乘数的列数一一对应或者是一对多
print(a/b)
print(a/aa)
print(aa/a)
print(aa/b)
print(b/aa)

[1. 2. 3.]
[[1. 1. 1.]
 [1. 1. 1.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[1. 2. 3.]
 [1. 2. 3.]]
[[1.         0.5        0.33333333]
 [1.         0.5        0.33333333]]


In [24]:
#“ + ”运算，普通乘法，对应位置做乘法,2个乘数的列数一一对应或者是一对多
print(a+b)
print(a+aa)
print(aa+a)
print(aa+b)
print(b+aa)

[2 3 4]
[[2 4 6]
 [2 4 6]]
[[2 4 6]
 [2 4 6]]
[[2 3 4]
 [2 3 4]]
[[2 3 4]
 [2 3 4]]


In [25]:
#“ - ”运算，普通乘法，对应位置做乘法,2个乘数的列数一一对应或者是一对多
print(a-b)
print(a-aa)
print(aa-a)
print(aa-b)
print(b-aa)
a*aa

[0 1 2]
[[0 0 0]
 [0 0 0]]
[[0 0 0]
 [0 0 0]]
[[0 1 2]
 [0 1 2]]
[[ 0 -1 -2]
 [ 0 -1 -2]]


array([[1, 4, 9],
       [1, 4, 9]])

In [ ]:
#总结
#四则运算（加减乘除），要求数组形状(shape)相同，或者是多维数组和一维度数组），如果n对m n不等于m，将报错。


In [9]:
#np.dot,点乘，向量乘法
#print(np.dot(a,b)), shapes (3,) and (1,) not aligned: 3 (dim 0) != 1 (dim 0)
#print(np.dot(a,aa))，shapes (3,) and (2,3) not aligned: 3 (dim 0) != 2 (dim 0)
print(np.dot(aa,a)) #行列点乘，2行3列*3行1列
#print(np.dot(aa,b)) shapes (2,3) and (1,) not aligned: 3 (dim 1) != 1 (dim 0)
print(np.dot(b,aa))


[14 14]


ValueError: shapes (1,) and (2,3) not aligned: 1 (dim 0) != 2 (dim 0)

In [ ]:
#np.dot ,行列点乘，被乘数的列数=乘数的行数，列数=行数